const express = require('express')
const router = express.Router()

const verify_email = require('../controlllers/admin/auth/verifyEmail')
const verify_otp = require('../controlllers/admin/auth/verifyOtp')
const authorize = require('../middleware/authorizeRole')
const authenticate = require('../middleware/authMiddleware')
const {getTotalCustomers,totalProducts, totalOrders, totalStocks, totalRevenue, MostSale} = require('../controlllers/admin/dashboard/dashboard')
const newProduct = require('../controlllers/admin/product/Product')
const upload = require('../middleware/multer')
const ProductList = require('../controlllers/admin/productList/productList')
const productDelete = require('../controlllers/admin/productDelete/productDelete')
const customerList = require('../controlllers/admin/customerList/customerList')
const { getAllOrdersWithItems } = require('../controlllers/admin/order/orders')

router.post('/verify_email',verify_email)
router.post('/verify_otp',verify_otp)
router.get('/dashboard',authenticate,authorize(['dashboard']),getTotalCustomers)
router.get('/totalproducts',authenticate,authorize(['dashboard']),totalProducts)
router.get('/totalOrders',authenticate,authorize(['dashboard']),totalOrders)
router.get('/totalStocks',authenticate,authorize(['dashboard']),totalStocks)
router.get('/totalRevenue',authenticate,authorize(['dashboard']),totalRevenue)
router.get('/MostSale',authenticate,authorize(['dashboard']),MostSale)
router.post('/new_product',authenticate,authorize(['product']),upload.single('image'),newProduct)
router.get('/product_list',authenticate,authorize(['productList']),ProductList)
router.get('/delete_product/:id',authenticate,authorize(['productList']),productDelete)
router.get('/customer_list',authenticate,authorize(['customerList']),customerList)
router.get('/orders',authenticate,authorize(['orders']),getAllOrdersWithItems)
module.exports = router