const express = require('express')
const router = express.Router()
const verifyEmail = require('../controlllers/customer/verifyEmail')
const verifyOtp = require('../controlllers/customer/verifyOtp')
const customerSIgnIn = require('../controlllers/customer/customerSIgnIn')
const verifyEmail_ForgotPassword = require('../controlllers/customer/verifyEmail_ForgotPassword')
const verifyOtp_ForgotPassword = require('../controlllers/customer/verifyOtp_ForgotPassword')
const verify_NewPassword = require('../controlllers/customer/verfiy_NewPassword')
const authorize = require('../middleware/authorizeRole')
const authenticate = require('../middleware/authMiddleware')
const productList = require('../controlllers/customer/productList/productLIist')
const productDetails = require('../controlllers/customer/productDetails/productDetails')
const addToCartController = require('../controlllers/customer/addToCart/addToCart')
const CartController = require('../controlllers/customer/cart/cart')
const deleteCartController = require('../controlllers/customer/deleteCart/deleteCart')
const { placeOrder } = require('../controlllers/customer/orderController/orderController')
const { getOrdersByStatus } = require('../controlllers/customer/orderStatusController/orderStatusController')

router.post('/verifyEmail',verifyEmail)
router.post('/verifyOtp',verifyOtp)
router.post('/customerSignIn',customerSIgnIn)
router.post('/verifyEmailPassword',verifyEmail_ForgotPassword)
router.post('/verifyOtp_forgotPassword',verifyOtp_ForgotPassword)
router.post('/verify_NewPassword',verify_NewPassword)
router.get('/product_list',authenticate,authorize(['productList']),productList)
router.get('/productDetails/:productId',authenticate,authorize(['productDetails']),productDetails)
router.post('/AddToCart',authenticate,authorize(['addToCart']),addToCartController)
router.get('/cart',authenticate,authorize(['cart']),CartController.cart)
router.get('/cart/:customerId',authenticate,authorize(['cart']),CartController.getCart)
router.delete('/deleteCart/:cartId',authenticate,authorize(['cart']),deleteCartController)
router.put('/cartQuantity/:cartId',authenticate,authorize(['cart'],),CartController.updateCartQuantityController)
router.post('/place_order', authenticate, authorize(['placeOrder']), placeOrder);
router.get('/status/:status',authenticate,authorize(['orders']),getOrdersByStatus)
module.exports = router;
